/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    Chart: typeof import('primevue/chart')['default']
    Column: typeof import('primevue/column')['default']
    ConnectionMonitor: typeof import('./src/components/shared/ConnectionMonitor.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    DateRangePicker: typeof import('./src/components/shared/DateRangePicker.vue')['default']
    Dg_HitoricUserConnections: typeof import('./src/components/Frm_Ajustes/Dg_HitoricUserConnections.vue')['default']
    DgHitoricUserConnections: typeof import('./src/components/Frm_Ajustes/DgHitoricUserConnections.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    GenericDataTable: typeof import('./src/components/shared/GenericDataTable.vue')['default']
    HistoricDialog: typeof import('./src/components/Frm_Ajustes/HistoricDialog.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    IftaLabel: typeof import('primevue/iftalabel')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ListGridUsers: typeof import('./src/components/Frm_Ajustes/ListGridUsers.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    OverlayBadge: typeof import('primevue/overlaybadge')['default']
    OverlayPanel: typeof import('primevue/overlaypanel')['default']
    Paginator: typeof import('primevue/paginator')['default']
    Password: typeof import('primevue/password')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('primevue/skeleton')['default']
    Tag: typeof import('primevue/tag')['default']
    Timeline: typeof import('primevue/timeline')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    UsuariosTabla: typeof import('./src/components/Frm_Ajustes/UsuariosTabla.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
