/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AttachmentsDialog: typeof import('./src/components/attachments/AttachmentsDialog.vue')['default']
    AttachmentsPanel: typeof import('./src/components/attachments/AttachmentsPanel.vue')['default']
    AttachmentsPreview: typeof import('./src/components/attachments/AttachmentsPreview.vue')['default']
    AttachmentsUpload: typeof import('./src/components/attachments/AttachmentsUpload.vue')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    BooleanFilter: typeof import('./src/components/shared/BooleanFilter.vue')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    Chart: typeof import('primevue/chart')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    CheckboxGroup: typeof import('primevue/checkboxgroup')['default']
    Chip: typeof import('primevue/chip')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    ConnectionMonitor: typeof import('./src/components/shared/ConnectionMonitor.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    DateRangePicker: typeof import('./src/components/shared/DateRangePicker.vue')['default']
    Dg_HitoricUserConnections: typeof import('./src/components/Frm_Ajustes/Dg_HitoricUserConnections.vue')['default']
    DgHitoricUserConnections: typeof import('./src/components/Frm_Ajustes/DgHitoricUserConnections.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DialogNotes: typeof import('./src/components/dialogs/DialogNotes.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    GenericDataTable: typeof import('./src/components/shared/GenericDataTable.vue')['default']
    HistoricDialog: typeof import('./src/components/Frm_Ajustes/HistoricDialog.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    IftaLabel: typeof import('primevue/iftalabel')['default']
    InlineMessage: typeof import('primevue/inlinemessage')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    KiwiLookup: typeof import('./src/components/shared/KiwiLookup/KiwiLookup.vue')['default']
    ListGridUsers: typeof import('./src/components/Frm_Ajustes/ListGridUsers.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    OverlayBadge: typeof import('primevue/overlaybadge')['default']
    OverlayPanel: typeof import('primevue/overlaypanel')['default']
    Paginator: typeof import('primevue/paginator')['default']
    Panel: typeof import('primevue/panel')['default']
    Password: typeof import('primevue/password')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Timeline: typeof import('primevue/timeline')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    UsuariosTabla: typeof import('./src/components/Frm_Ajustes/UsuariosTabla.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
