<template>
  <section class="chain-panel">
    <header><div><b><i class="pi pi-link"/> Encadenamiento VeriFactu</b><small>Las 8 últimas huellas archivadas y su enlace con el registro anterior</small></div><div class="chain-actions"><label><span>Desde</span><DatePicker v-model="dateFrom" dateFormat="dd/mm/yy" showIcon placeholder="Sin límite"/></label><label><span>Hasta</span><DatePicker v-model="dateTo" dateFormat="dd/mm/yy" showIcon placeholder="Sin límite"/></label><Button label="Aplicar" icon="pi pi-filter" size="small" :loading="loading" @click="load"/><Button v-if="dateFrom||dateTo" icon="pi pi-filter-slash" text rounded title="Quitar rango" @click="clearRange"/><Button icon="pi pi-refresh" text rounded :loading="loading" title="Actualizar cadena" @click="load"/><Button :icon="expanded?'pi pi-chevron-up':'pi pi-chevron-down'" text rounded @click="expanded=!expanded"/></div></header>
    <div v-if="expanded" class="chain-body">
      <div v-if="loading" class="loading"><i class="pi pi-spin pi-spinner"/> Comprobando el encadenamiento…</div>
      <Message v-else-if="!rows.length" severity="info" :closable="false">Aún no hay registros VeriFactu archivados.</Message>
      <div v-else class="chain-list">
        <article v-for="(item,index) in rows" :key="item.historicId" :class="{broken:!item.firstRecord&&!item.previousHash}">
          <div class="chain-state"><i :class="item.firstRecord?'pi pi-flag':item.accepted?'pi pi-check-circle':'pi pi-exclamation-triangle'"/><span v-if="index<rows.length-1"/></div>
          <div class="chain-data"><div><b>{{item.code}}</b><Tag :value="item.firstRecord?'Primer registro':item.accepted?'Encadenada':'Revisar'" :severity="item.firstRecord||item.accepted?'success':'warn'" rounded/></div><small>{{dateTime(item.date)}}</small><section><span><small>Huella del registro</small><code :title="item.currentHash">{{shortHash(item.currentHash)}}</code></span><i class="pi pi-arrow-left"/><span><small>{{item.firstRecord?'Inicio de la cadena':'Factura anterior · '+(item.previousCode||'sin identificar')}}</small><code v-if="!item.firstRecord" :title="item.previousHash">{{shortHash(item.previousHash)}}</code><b v-else>PrimerRegistro = S</b></span></section></div>
        </article>
      </div>
    </div>
  </section>
</template>
<script setup lang="ts">
import{onMounted,ref}from'vue';import axios from'axios';import Button from'primevue/button';import DatePicker from'primevue/datepicker';import Message from'primevue/message';import Tag from'primevue/tag';
const expanded=ref(true),loading=ref(false),rows=ref<any[]>([]),dateFrom=ref<Date|null>(null),dateTo=ref<Date|null>(null),pad=(v:number)=>String(v).padStart(2,'0');
const dateTime=(v:any)=>{const d=Array.isArray(v)?new Date(v[0],v[1]-1,v[2],v[3]||0,v[4]||0,v[5]||0):new Date(v);return Number.isNaN(d.getTime())?'—':`${pad(d.getDate())}/${pad(d.getMonth()+1)}/${d.getFullYear()} ${pad(d.getHours())}:${pad(d.getMinutes())}`},shortHash=(v:string)=>v?`${v.slice(0,12)}…${v.slice(-8)}`:'Sin huella';
const isoDay=(value:Date|null)=>value?`${value.getFullYear()}-${pad(value.getMonth()+1)}-${pad(value.getDate())}`:undefined;
const load=async()=>{loading.value=true;try{rows.value=(await axios.get(`${import.meta.env.VITE_API_URL}/WebGetSalesInvoiceVeriFactuChain`,{params:{from:isoDay(dateFrom.value),to:isoDay(dateTo.value)}})).data||[]}finally{loading.value=false}},clearRange=()=>{dateFrom.value=null;dateTo.value=null;load()};onMounted(load);
</script>
<style scoped>
.chain-panel{margin-top:14px;overflow:hidden;border:1px solid #dfe4ea;border-radius:14px;background:#fff}.chain-panel>header{display:flex;align-items:center;justify-content:space-between;padding:13px 16px;border-bottom:1px solid #e8ecf0}.chain-panel>header>div:last-child{display:flex}.chain-panel header i{color:#648506}.chain-panel header small{display:block;margin-top:.2rem;color:#7d8797}.chain-body{padding:14px 16px}.loading{display:flex;justify-content:center;gap:.5rem;padding:2rem}.chain-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.7rem 1.2rem}.chain-list article{display:flex;min-width:0;gap:.65rem;padding:.7rem;border:1px solid #e3ead3;border-radius:10px;background:#fafcf7}.chain-list article.broken{border-color:#efcece;background:#fff8f8}.chain-state{display:flex;align-items:center;flex-direction:column;color:#648506}.chain-state>i{display:grid;width:30px;height:30px;place-items:center;border-radius:50%;background:#eaf2d2}.chain-state>span{width:2px;flex:1;margin-top:.3rem;background:#cbdba0}.chain-data{min-width:0;flex:1}.chain-data>div{display:flex;align-items:center;justify-content:space-between;gap:.4rem}.chain-data>small{color:#7d8797;font-size:.7rem}.chain-data section{display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr);align-items:center;gap:.6rem;margin-top:.55rem;padding:.55rem;border-radius:8px;background:#fff}.chain-data section span{min-width:0}.chain-data section small,.chain-data section code,.chain-data section b{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.chain-data section small{color:#7d8797;font-size:.66rem}.chain-data section code{margin-top:.2rem;color:#34431a;font-size:.69rem}.chain-data section>i{color:#8aa13e}@media(max-width:900px){.chain-list{grid-template-columns:1fr}}
.chain-actions{display:flex;align-items:flex-end;gap:.35rem}.chain-actions label{display:flex;flex-direction:column;gap:.2rem}.chain-actions label>span{color:#7d8797;font-size:.65rem;font-weight:700}.chain-actions :deep(.p-datepicker){width:145px}.chain-actions :deep(.p-inputtext){padding:.4rem .5rem;font-size:.78rem}@media(max-width:1050px){.chain-panel>header{align-items:flex-start;flex-direction:column}.chain-actions{width:100%;flex-wrap:wrap}}
</style>
